sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: qLxBmtKeCjLKIMjbTb+MSHaW/hEv7wOGrcWi9U5JvJYDvLAuiHe0IsVGdOs2gh9ApQOIRL9Ea75hy/nbfSdJ7WJDo6p7LoQ36rlLCxH2O+FX5w7ElrfQCUXG1XcZ0Xgldmw0uOTdjFz5CyfZc1EQG6IDO9H9FH19Eys0llRGIovuhd/Et9yvdbjzy4lJImc7Nmn1VQpk/DoQyn0O7ELRpbxvJPqZ/dV+8JgtU193nnTe7xIDoPDx61NQveVu1nGgbWF5Fbd2yMCWiGDl+Bmhx3pHN+LYqJNI9CWhJkMWOd55WPtCDGToPlwVXztn516FhelDJceDDh5mhf0m1ZEHi4Q2mP8d36a+3KdRPdfs/mFvWgAodGJcSmExk9AoWg+WNm2pR5JxDyXpot90q4R6yuYvs8TpW7v83H1eiN4Mkz0aA2GlgFH3Y41PRmIl3xhtmx7rD5UunEiPM24SRI2C9ezM2MS7NTTScS7TztoRfe4tVtNvAgp/QLQm7V/MZoK+7li4D+/qPn/3oLFkYSpL61084nT/GOv59Xo/2tLe04MJwIbyNkNfyOih9u2Xn3A7wViSRjtPoDsUb6pCjwrKrcxKBFxt7sMoO2tguY102+2z5NrxnAv5XWf33vi7+49497rb9i9ztcsVgCuHCjdgPCVWMUgB2uGEIjEbV9emNg8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Romeo-and-Juliet_1513
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy